### ISSUE TITLE
.net standard

### ISSUE THREAD

**Issue by neutmute** [richardszalay/pshosts#15]
Hi Richard - I'd like to convert your c# Hosts assembly to .NET standard 1.x (whatever the lowest is supported).
I'd also like this to be published as a nuget package. 
I'd control the nuget package publish via an environment variable so that you could set the api key on your build server and have it publish under your account.

Would you be open to a PR making these changes?

The reason for these requests is I have a dot net core app to help provision servers in my Octopus deploy pipeline. I need to hack the hosts file of the server programmatically.

**Comment by richardszalay** [comment]
Hi @neutmute,

Interesting proposal. I had considered releasing the core library on NuGet but never got around to it.

I'd be happy to accept a PR, as long as:

* It had it's own .sln and .csproj (I need the existing one targetting .NET 4 in order to support PowerShell 3)
* It had it's own Psake build file

As a low-fi alternative, you can also copy the code into your library (it's only a few files, and they could be combined).

Rich

**Comment by neutmute** [comment]
Yeah ok - does seem like a lot of work for a few files :) I'll roll with the low fi - thanks!
